#!/usr/bin/env python3
"""Embed web/index.html gzip-compressed into src/net/web_page.h.

Runs as a PlatformIO pre-build script (extra_scripts = pre:tools/embed_web.py)
and can be run by hand: python3 tools/embed_web.py
"""
import gzip
import os

try:
    Import("env")  # noqa: F821  (PlatformIO / SCons)
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(ROOT, "web", "index.html")
DST = os.path.join(ROOT, "src", "net", "web_page.h")


def embed():
    with open(SRC, "rb") as f:
        html = f.read()
    gz = gzip.compress(html, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(gz), 20):
        lines.append("    " + ", ".join("0x%02x" % b for b in gz[i:i + 20]) + ",")
    out = (
        "// Generated by tools/embed_web.py from web/index.html - do not edit.\n"
        "#pragma once\n#include <stddef.h>\n#include <stdint.h>\n#include <pgmspace.h>\n\n"
        "static const size_t WEB_INDEX_GZ_LEN = %d;  // %d bytes uncompressed\n"
        "static const uint8_t WEB_INDEX_GZ[] PROGMEM = {\n%s\n};\n" % (len(gz), len(html), "\n".join(lines))
    )
    old = None
    if os.path.exists(DST):
        with open(DST, "r") as f:
            old = f.read()
    if old != out:
        with open(DST, "w") as f:
            f.write(out)
        print("embed_web: %s (%d -> %d bytes gzip)" % (os.path.relpath(DST, ROOT), len(html), len(gz)))


embed()
